### PR TITLE
add background image

### PR DESCRIPTION
**Pull request by iambk**
Added banner.jpg which got deleted previously.
Fixed style.css to include it properly.

### CODE REVIEW

**Comment by adtya** [comment]
you have to use `/assets/banner.jpg` or it won't get loaded in pages other than pages from the root directory

**Comment by iambk** [comment]
> you have to use `/assets/banner.jpg` or it won't get loaded in pages other than pages from the root directory

Modified accordingly

**Comment by akhilseshan** [comment]
Thank you for contributing.

**Comment by akhilseshan** [comment]
🤣

**Pull request merged**
